services:
  - type: web
    name: your-project-name
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate && gunicorn your_project_name.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4